### ISSUE TITLE
Add pull request template to each repository

### ISSUE THREAD

**Issue by DiamondDragon** [GodelTech/GodelTech.Microservices.Core#26]
When pull request template is created important information must be added to description. In order to simplify this activity it's suggested to create `.github` folder and pull template named `PULL_REQUEST_TEMPLATE.md`.

More details can be found here: 

* https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
* https://embeddedartistry.com/blog/2017/08/04/a-github-pull-request-template-for-your-projects/

**Comment by DiamondDragon** [comment]
Here is how pull request template content may look like:

```plain
##### CHANGE TYPE
<!--- MANDATORY: Delete the items that don't apply -->
 - Patch
 - Minor
 - Major

##### GitHub issue link
<!--- MANDATORY: Add the GitHub issue url here -->

##### IMPACT, DEPENDENCIES AND TEST CONSIDERATIONS
<!--- Describe the likely impact of this change -->
<!--- Describe any dependencies this change may have on other changes in the pipeline, if any -->

```

**Comment by Pavel-Lapatin** [comment]
Bug report and feature request template should be changed:
1. Prioraty should be removed from bug report.
2. Acceptance Creteria should be removed from feature request.
