### ISSUE TITLE
Create Lambda function host application

### ISSUE THREAD

**Issue by DiamondDragon** [GodelTech/GodelTech.Microservices.Core#30]
It looks like good idea to create example\project which allows microservice framework to be hosted inside AWS\Azure lambda function. Integration of existing framework with lambda function should be relatively easy activity.

Main use case which is covered by this example is creation of service\website which is rarely invoked and execution as separate application looks like vast of  resources.

**Comment by Pavel-Lapatin** [comment]
Example was added into GodelTech.Microservices.Examples repository.
