### ISSUE TITLE
Move AccessTokenMiddleware and BearerTokenStorage to GodelTech.Microservices.Http

### ISSUE THREAD

**Issue by DiamondDragon** [GodelTech/GodelTech.Microservices.Core#31]
Move AccessTokenMiddleware and BearerTokenStorage to GodelTech.Microservices.Http. At the moment it looks like the only usage if these components can be found in service client project. it makes sense to move these components to  GodelTech.Microservices.Http.

**Comment by toustsik** [comment]
Please check a pull requests:

https://github.com/GodelTech/GodelTech.Microservices.Core/pull/32

**Comment by toustsik** [comment]
Please, check a pull request:

https://github.com/GodelTech/GodelTech.Microservices.Http/pull/1
