### ISSUE TITLE
Add definitions for user-defined types and members to generate clear xml document

### ISSUE THREAD

**Issue by Pavel-Lapatin** [GodelTech/GodelTech.Microservices.Core#40]
#### DESCRIPTION

Add definitions for user-defined types and members to generate clear xml document It helps users who does not have access to code understand how they should use framework. Also this document could be used with some tools.
#### ADDITIONAL CONTEXT

Description about xml documents and tags you can find here: https://docs.microsoft.com/en-us/dotnet/csharp/codedoc

**Comment by DiamondDragon** [comment]
I would suggest to treat documentation warnings as errors messages in order to force developer creating documentation.
